apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-imzp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-imzp@sha256:fc1f4c26b7c1aa0d617db8b5b15223e323fcd340fffc14c7be28d90a3f93664e
        name: my-nodejs
        resources: {}
status: {}
